disabled_rules:
  - trailing_comma
  - identifier_name
  - void_return
  - operator_whitespace
  - nesting
  - cyclomatic_complexity
  - multiple_closures_with_trailing_closure
  - type_name
  - todo
  - opening_brace
  - comment_spacing

line_length: 120

function_body_length:
  - 50

included:
  - Sources
  - Tests
