name: Swift

on:
  push:
    branches: [main]
  pull_request:

jobs:
  macos_build:
    strategy:
      matrix:
        include:
          - xcode: "12.4" # Swift 5.3
            macos: "10.15"

          - xcode: "13.0" # Swift 5.5
            macos: "11"

    runs-on: macos-${{ matrix.macos }}

    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer/
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test

  ubuntu_build:
    strategy:
      matrix:
        swift:
          - "5.4"
          - "5.5"

    runs-on: ubuntu-20.04
    container:
        image: swift:${{ matrix.swift }}
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test --enable-test-discovery

  windows_build:
    strategy:
      matrix:
        swift:
          - "5.4"
          - "5.5"

    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - uses: MaxDesiatov/swift-windows-action@v1
        with:
          shell-action: swift build
          swift-version: ${{ matrix.swift }}
# FIXME: re-enable tests when SnapshotTesting is available on Windows.
#       - name: Run tests
#         run: swift test
