name: Swift

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  macos_build:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test

  ubuntu_build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
