name: Swift

on:
  push:
    branches: [main]
  pull_request:

jobs:
  macos_build:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode 13.0
        run: sudo xcode-select --switch /Applications/Xcode_13.0.app/Contents/Developer/
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test

  ubuntu_build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test

  windows_build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - uses: MaxDesiatov/swift-windows-action@v1
        with:
          shell-action: swift build
# FIXME: re-enable tests when SnapshotTesting is available on Windows.
#       - name: Run tests
#         run: swift test
